"""Additional animals for Extinct/Endangered and Deep Sea/Marine pages."""

NEW_ANIMALS = [
    # ═══════════════════════════════════════════════════════════════
    # EXTINCT & CRITICALLY ENDANGERED (25 animals)
    # ═══════════════════════════════════════════════════════════════
    {"common_name": "Dodo", "scientific_name": "Raphus cucullatus",
     "class_name": "Aves", "order_name": "Columbiformes", "family_name": "Columbidae", "genus": "Raphus",
     "diet": "Omnivore", "conservation_code": "EX", "continent_code": "AF", "biome": "Tropical Forest", "environment_type": "terrestrial",
     "lifespan": "~20 years", "average_weight": "10-18 kg",
     "description": "The dodo was a flightless bird endemic to Mauritius, driven to extinction by the late 17th century due to hunting and introduced predators.",
     "habitat_summary": "Forests and coastal areas of Mauritius.",
     "wiki_title": "Dodo",
     "countries": ["MG"], "occurrences": [(-20.35, 57.55)]},

    {"common_name": "Thylacine", "scientific_name": "Thylacinus cynocephalus",
     "class_name": "Mammalia", "order_name": "Dasyuromorphia", "family_name": "Thylacinidae", "genus": "Thylacinus",
     "diet": "Carnivore", "conservation_code": "EX", "continent_code": "OC", "biome": "Temperate Forest", "environment_type": "terrestrial",
     "lifespan": "5-7 years", "average_weight": "20-30 kg",
     "description": "The Tasmanian tiger was the largest known carnivorous marsupial of modern times. The last confirmed individual died in Hobart Zoo in 1936.",
     "habitat_summary": "Eucalyptus forests, wetlands, and grasslands of Tasmania and mainland Australia.",
     "wiki_title": "Thylacine",
     "countries": ["AU"], "occurrences": [(-42.0, 146.0)]},

    {"common_name": "Passenger Pigeon", "scientific_name": "Ectopistes migratorius",
     "class_name": "Aves", "order_name": "Columbiformes", "family_name": "Columbidae", "genus": "Ectopistes",
     "diet": "Herbivore", "conservation_code": "EX", "continent_code": "NA", "biome": "Temperate Forest", "environment_type": "terrestrial",
     "lifespan": "~15 years", "average_weight": "260-340 g",
     "description": "Once the most abundant bird in North America with flocks numbering in the billions, the passenger pigeon was hunted to extinction by 1914.",
     "habitat_summary": "Deciduous forests of eastern North America.",
     "wiki_title": "Passenger pigeon",
     "countries": ["US", "CA"], "occurrences": [(40.0, -83.0), (44.0, -79.0)]},

    {"common_name": "Quagga", "scientific_name": "Equus quagga quagga",
     "class_name": "Mammalia", "order_name": "Perissodactyla", "family_name": "Equidae", "genus": "Equus",
     "diet": "Herbivore", "conservation_code": "EX", "continent_code": "AF", "biome": "Grassland", "environment_type": "terrestrial",
     "lifespan": "~20 years", "average_weight": "250-300 kg",
     "description": "A subspecies of the plains zebra distinguished by its limited striping pattern. The last quagga died in Amsterdam Zoo in 1883.",
     "habitat_summary": "Grasslands and karoo of South Africa.",
     "wiki_title": "Quagga",
     "countries": ["ZA"], "occurrences": [(-31.5, 19.0)]},

    {"common_name": "Great Auk", "scientific_name": "Pinguinus impennis",
     "class_name": "Aves", "order_name": "Charadriiformes", "family_name": "Alcidae", "genus": "Pinguinus",
     "diet": "Carnivore", "conservation_code": "EX", "continent_code": "EU", "biome": "Ocean", "environment_type": "marine",
     "lifespan": "~20 years", "average_weight": "5 kg",
     "description": "A flightless seabird of the North Atlantic, the great auk was hunted to extinction by the mid-19th century for its feathers, meat, and oil.",
     "habitat_summary": "Rocky islands and coastal waters of the North Atlantic.",
     "wiki_title": "Great auk",
     "countries": ["IS", "GB", "CA"], "occurrences": [(63.8, -22.7), (47.2, -52.8)]},

    {"common_name": "Steller's Sea Cow", "scientific_name": "Hydrodamalis gigas",
     "class_name": "Mammalia", "order_name": "Sirenia", "family_name": "Dugongidae", "genus": "Hydrodamalis",
     "diet": "Herbivore", "conservation_code": "EX", "continent_code": "AS", "biome": "Ocean", "environment_type": "marine",
     "lifespan": "~50 years", "average_weight": "8000-10000 kg",
     "description": "A massive marine mammal up to 9 metres long discovered in 1741 and hunted to extinction within 27 years by fur traders.",
     "habitat_summary": "Shallow coastal waters around the Commander Islands in the Bering Sea.",
     "wiki_title": "Steller's sea cow",
     "countries": ["RU"], "occurrences": [(55.2, 166.0)]},

    {"common_name": "Woolly Mammoth", "scientific_name": "Mammuthus primigenius",
     "class_name": "Mammalia", "order_name": "Proboscidea", "family_name": "Elephantidae", "genus": "Mammuthus",
     "diet": "Herbivore", "conservation_code": "EX", "continent_code": "EU", "biome": "Tundra", "environment_type": "terrestrial",
     "lifespan": "60-80 years", "average_weight": "4000-6000 kg",
     "description": "One of the most iconic Ice Age creatures, the woolly mammoth roamed the frozen steppes of Eurasia and North America before going extinct ~4,000 years ago.",
     "habitat_summary": "Mammoth steppe — cold, dry grasslands and tundra across northern Eurasia and North America.",
     "wiki_title": "Woolly mammoth",
     "countries": ["RU", "US", "CA", "GB"], "occurrences": [(64.0, 100.0), (63.0, -145.0)]},

    {"common_name": "Sabre-toothed Tiger", "scientific_name": "Smilodon fatalis",
     "class_name": "Mammalia", "order_name": "Carnivora", "family_name": "Felidae", "genus": "Smilodon",
     "diet": "Carnivore", "conservation_code": "EX", "continent_code": "NA", "biome": "Grassland", "environment_type": "terrestrial",
     "lifespan": "~20 years", "average_weight": "160-280 kg",
     "description": "Smilodon was a genus of machairodont felid famous for its elongated canine teeth up to 28 cm long. It went extinct roughly 10,000 years ago.",
     "habitat_summary": "Grasslands, shrubby woodlands, and open areas of the Americas.",
     "wiki_title": "Smilodon",
     "countries": ["US", "BR", "AR"], "occurrences": [(34.0, -118.2), (-34.6, -58.4)]},

    {"common_name": "Baiji", "scientific_name": "Lipotes vexillifer",
     "class_name": "Mammalia", "order_name": "Artiodactyla", "family_name": "Lipotidae", "genus": "Lipotes",
     "diet": "Carnivore", "conservation_code": "CR", "continent_code": "AS", "biome": "Freshwater", "environment_type": "freshwater",
     "lifespan": "~24 years", "average_weight": "135-230 kg",
     "description": "The Yangtze river dolphin, or baiji, is functionally extinct — a 2006 survey failed to find a single individual. It is the first dolphin driven to extinction by humans.",
     "habitat_summary": "Yangtze River, China.",
     "wiki_title": "Baiji",
     "countries": ["CN"], "occurrences": [(30.6, 114.3)]},

    {"common_name": "Western Black Rhinoceros", "scientific_name": "Diceros bicornis longipes",
     "class_name": "Mammalia", "order_name": "Perissodactyla", "family_name": "Rhinocerotidae", "genus": "Diceros",
     "diet": "Herbivore", "conservation_code": "EX", "continent_code": "AF", "biome": "Savanna", "environment_type": "terrestrial",
     "lifespan": "35-50 years", "average_weight": "800-1400 kg",
     "description": "The western black rhinoceros was declared extinct in 2011 after extensive poaching for its horn decimated the population.",
     "habitat_summary": "Savannas and shrublands of western and central Africa.",
     "wiki_title": "Western black rhinoceros",
     "countries": ["CM", "NG"], "occurrences": [(7.5, 12.0)]},

    {"common_name": "Pyrenean Ibex", "scientific_name": "Capra pyrenaica pyrenaica",
     "class_name": "Mammalia", "order_name": "Artiodactyla", "family_name": "Bovidae", "genus": "Capra",
     "diet": "Herbivore", "conservation_code": "EX", "continent_code": "EU", "biome": "Alpine", "environment_type": "terrestrial",
     "lifespan": "~12 years", "average_weight": "24-80 kg",
     "description": "Also known as the bucardo, the Pyrenean ibex went extinct in 2000. A brief cloning attempt in 2003 produced a kid that lived only 7 minutes.",
     "habitat_summary": "Rocky mountain terrain of the Pyrenees between Spain and France.",
     "wiki_title": "Pyrenean ibex",
     "countries": ["ES", "FR"], "occurrences": [(42.7, 0.0)]},

    {"common_name": "Javan Rhinoceros", "scientific_name": "Rhinoceros sondaicus",
     "class_name": "Mammalia", "order_name": "Perissodactyla", "family_name": "Rhinocerotidae", "genus": "Rhinoceros",
     "diet": "Herbivore", "conservation_code": "CR", "continent_code": "AS", "biome": "Tropical Rainforest", "environment_type": "terrestrial",
     "lifespan": "30-45 years", "average_weight": "900-2300 kg",
     "description": "With fewer than 80 individuals remaining in a single national park, the Javan rhinoceros is the rarest large mammal on Earth.",
     "habitat_summary": "Lowland tropical rainforests of Ujung Kulon National Park, Java, Indonesia.",
     "wiki_title": "Javan rhinoceros",
     "countries": ["ID"], "occurrences": [(-6.75, 105.33)]},

    {"common_name": "Vaquita", "scientific_name": "Phocoena sinus",
     "class_name": "Mammalia", "order_name": "Artiodactyla", "family_name": "Phocoenidae", "genus": "Phocoena",
     "diet": "Carnivore", "conservation_code": "CR", "continent_code": "NA", "biome": "Ocean", "environment_type": "marine",
     "lifespan": "~21 years", "average_weight": "30-55 kg",
     "description": "The world's rarest marine mammal with fewer than 10 individuals remaining. This small porpoise is found only in the Gulf of California.",
     "habitat_summary": "Shallow, murky waters of the northern Gulf of California, Mexico.",
     "wiki_title": "Vaquita",
     "countries": ["MX"], "occurrences": [(31.0, -114.5)]},

    {"common_name": "Sumatran Rhinoceros", "scientific_name": "Dicerorhinus sumatrensis",
     "class_name": "Mammalia", "order_name": "Perissodactyla", "family_name": "Rhinocerotidae", "genus": "Dicerorhinus",
     "diet": "Herbivore", "conservation_code": "CR", "continent_code": "AS", "biome": "Tropical Rainforest", "environment_type": "terrestrial",
     "lifespan": "35-40 years", "average_weight": "500-800 kg",
     "description": "The smallest and most ancient living rhinoceros, with fewer than 80 left in fragmented populations across Sumatra and Borneo.",
     "habitat_summary": "Dense tropical and subtropical mountain forests of Indonesia and Malaysia.",
     "wiki_title": "Sumatran rhinoceros",
     "countries": ["ID", "MY"], "occurrences": [(-0.5, 101.5), (4.5, 117.5)]},

    {"common_name": "Yangtze Giant Softshell Turtle", "scientific_name": "Rafetus swinhoei",
     "class_name": "Reptilia", "order_name": "Testudines", "family_name": "Trionychidae", "genus": "Rafetus",
     "diet": "Omnivore", "conservation_code": "CR", "continent_code": "AS", "biome": "Freshwater", "environment_type": "freshwater",
     "lifespan": "~100 years", "average_weight": "~100 kg",
     "description": "The world's rarest turtle with only a handful of known individuals. It can weigh over 100 kg and grow to nearly 1 metre long.",
     "habitat_summary": "Lakes and rivers in China and Vietnam.",
     "wiki_title": "Yangtze giant softshell turtle",
     "countries": ["CN", "VN"], "occurrences": [(21.0, 105.8)]},

    {"common_name": "Northern White Rhinoceros", "scientific_name": "Ceratotherium simum cottoni",
     "class_name": "Mammalia", "order_name": "Perissodactyla", "family_name": "Rhinocerotidae", "genus": "Ceratotherium",
     "diet": "Herbivore", "conservation_code": "CR", "continent_code": "AF", "biome": "Savanna", "environment_type": "terrestrial",
     "lifespan": "40-50 years", "average_weight": "1700-2400 kg",
     "description": "Functionally extinct with only two females remaining, both at Ol Pejeta Conservancy in Kenya. Scientists are attempting IVF to save the subspecies.",
     "habitat_summary": "Grasslands and savannas of central and east Africa.",
     "wiki_title": "Northern white rhinoceros",
     "countries": ["KE"], "occurrences": [(0.0, 36.9)]},

    {"common_name": "Spix's Macaw", "scientific_name": "Cyanopsitta spixii",
     "class_name": "Aves", "order_name": "Psittaciformes", "family_name": "Psittacidae", "genus": "Cyanopsitta",
     "diet": "Herbivore", "conservation_code": "EW", "continent_code": "SA", "biome": "Arid Shrubland", "environment_type": "terrestrial",
     "lifespan": "~28 years", "average_weight": "300 g",
     "description": "Known as the 'Blue Macaw' that inspired the film Rio, Spix's macaw is extinct in the wild with around 180 individuals in captive breeding programs.",
     "habitat_summary": "Gallery woodland along seasonal creeks in the caatinga of Bahia, Brazil.",
     "wiki_title": "Spix's macaw",
     "countries": ["BR"], "occurrences": [(-9.6, -39.1)]},

    {"common_name": "Hawaiian Crow", "scientific_name": "Corvus hawaiiensis",
     "class_name": "Aves", "order_name": "Passeriformes", "family_name": "Corvidae", "genus": "Corvus",
     "diet": "Omnivore", "conservation_code": "EW", "continent_code": "NA", "biome": "Tropical Forest", "environment_type": "terrestrial",
     "lifespan": "~18 years", "average_weight": "485 g",
     "description": "The ʻalalā is one of the most intelligent birds, capable of using tools. It went extinct in the wild in 2002 and is the subject of active reintroduction efforts.",
     "habitat_summary": "Montane tropical forests of Hawaii Island.",
     "wiki_title": "Hawaiian crow",
     "countries": ["US"], "occurrences": [(19.5, -155.5)]},

    {"common_name": "Scimitar-horned Oryx", "scientific_name": "Oryx dammah",
     "class_name": "Mammalia", "order_name": "Artiodactyla", "family_name": "Bovidae", "genus": "Oryx",
     "diet": "Herbivore", "conservation_code": "EW", "continent_code": "AF", "biome": "Desert", "environment_type": "terrestrial",
     "lifespan": "~20 years", "average_weight": "140-210 kg",
     "description": "Once ranging across the entire Sahel, the scimitar-horned oryx was declared extinct in the wild in 2000. Reintroduction programs in Chad have established a new wild population.",
     "habitat_summary": "Semi-desert and steppe grasslands of the Sahel region.",
     "wiki_title": "Scimitar oryx",
     "countries": ["SD", "NG", "CM"], "occurrences": [(15.5, 18.7)]},

    {"common_name": "Ivory-billed Woodpecker", "scientific_name": "Campephilus principalis",
     "class_name": "Aves", "order_name": "Piciformes", "family_name": "Picidae", "genus": "Campephilus",
     "diet": "Omnivore", "conservation_code": "CR", "continent_code": "NA", "biome": "Temperate Forest", "environment_type": "terrestrial",
     "lifespan": "~15 years", "average_weight": "450-570 g",
     "description": "Known as the 'Lord God Bird' for its stunning appearance, the ivory-billed woodpecker is likely extinct though occasional unconfirmed sightings keep hope alive.",
     "habitat_summary": "Old-growth bottomland hardwood forests of the southeastern United States.",
     "wiki_title": "Ivory-billed woodpecker",
     "countries": ["US", "CU"], "occurrences": [(34.8, -92.0), (22.0, -80.0)]},

    {"common_name": "Caribbean Monk Seal", "scientific_name": "Neomonachus tropicalis",
     "class_name": "Mammalia", "order_name": "Carnivora", "family_name": "Phocidae", "genus": "Neomonachus",
     "diet": "Carnivore", "conservation_code": "EX", "continent_code": "NA", "biome": "Ocean", "environment_type": "marine",
     "lifespan": "~20 years", "average_weight": "170-270 kg",
     "description": "The only seal species to go extinct due to human causes. The Caribbean monk seal was last confirmed seen in 1952 at Serranilla Bank.",
     "habitat_summary": "Tropical waters, beaches, and reefs of the Caribbean Sea and Gulf of Mexico.",
     "wiki_title": "Caribbean monk seal",
     "countries": ["CU", "MX", "US"], "occurrences": [(18.0, -78.0)]},

    {"common_name": "Golden Toad", "scientific_name": "Incilius periglenes",
     "class_name": "Amphibia", "order_name": "Anura", "family_name": "Bufonidae", "genus": "Incilius",
     "diet": "Insectivore", "conservation_code": "EX", "continent_code": "NA", "biome": "Tropical Rainforest", "environment_type": "terrestrial",
     "lifespan": "~12 years", "average_weight": "5 g",
     "description": "A strikingly brilliant orange toad once found only in a small area of Costa Rica's cloud forests. Last seen in 1989, it became a symbol of amphibian decline worldwide.",
     "habitat_summary": "Elfin cloud forests of Monteverde, Costa Rica.",
     "wiki_title": "Golden toad",
     "countries": ["CR"], "occurrences": [(10.3, -84.8)]},

    {"common_name": "Tasmanian Devil", "scientific_name": "Sarcophilus harrisii",
     "class_name": "Mammalia", "order_name": "Dasyuromorphia", "family_name": "Dasyuridae", "genus": "Sarcophilus",
     "diet": "Carnivore", "conservation_code": "EN", "continent_code": "OC", "biome": "Temperate Forest", "environment_type": "terrestrial",
     "lifespan": "5-8 years", "average_weight": "8-14 kg",
     "description": "The world's largest surviving carnivorous marsupial, threatened by a transmissible facial tumour disease that has decimated populations since 1996.",
     "habitat_summary": "Eucalyptus forests, woodlands, and coastal scrub of Tasmania.",
     "wiki_title": "Tasmanian devil",
     "countries": ["AU"], "occurrences": [(-42.0, 146.5)]},

    {"common_name": "Kakapo", "scientific_name": "Strigops habroptilus",
     "class_name": "Aves", "order_name": "Psittaciformes", "family_name": "Strigopidae", "genus": "Strigops",
     "diet": "Herbivore", "conservation_code": "CR", "continent_code": "OC", "biome": "Temperate Forest", "environment_type": "terrestrial",
     "lifespan": "40-80 years", "average_weight": "2-4 kg",
     "description": "The world's only flightless parrot and one of the longest-living birds. Intensive conservation has brought numbers from 51 to over 250.",
     "habitat_summary": "Predator-free offshore islands of New Zealand.",
     "wiki_title": "Kakapo",
     "countries": ["NZ"], "occurrences": [(-46.1, 166.7)]},

    {"common_name": "Saola", "scientific_name": "Pseudoryx nghetinhensis",
     "class_name": "Mammalia", "order_name": "Artiodactyla", "family_name": "Bovidae", "genus": "Pseudoryx",
     "diet": "Herbivore", "conservation_code": "CR", "continent_code": "AS", "biome": "Tropical Rainforest", "environment_type": "terrestrial",
     "lifespan": "~11 years", "average_weight": "80-100 kg",
     "description": "Discovered only in 1992, the saola is one of the world's rarest mammals. Sometimes called the 'Asian unicorn', it has never been seen by a biologist in the wild.",
     "habitat_summary": "Wet evergreen forests of the Annamite Mountains along the Laos-Vietnam border.",
     "wiki_title": "Saola",
     "countries": ["VN", "LA"], "occurrences": [(18.3, 105.0)]},

    # ═══════════════════════════════════════════════════════════════
    # DEEP SEA & MARINE ANIMALS (25 animals)
    # ═══════════════════════════════════════════════════════════════
    {"common_name": "Anglerfish", "scientific_name": "Lophius piscatorius",
     "class_name": "Actinopterygii", "order_name": "Lophiiformes", "family_name": "Lophiidae", "genus": "Lophius",
     "diet": "Carnivore", "conservation_code": "LC", "continent_code": "EU", "biome": "Ocean", "environment_type": "marine",
     "lifespan": "~25 years", "average_weight": "11-57 kg",
     "description": "Deep-sea anglerfish lure prey with a bioluminescent appendage dangling above their enormous jaws. Males are tiny and fuse permanently to the female's body.",
     "habitat_summary": "Deep ocean floors and midwater columns worldwide, 200-2000 m depth.",
     "wiki_title": "Anglerfish",
     "countries": ["GB", "NO", "FR"], "occurrences": [(48.0, -8.0), (62.0, 5.0)]},

    {"common_name": "Giant Squid", "scientific_name": "Architeuthis dux",
     "class_name": "Cephalopoda", "order_name": "Oegopsida", "family_name": "Architeuthidae", "genus": "Architeuthis",
     "diet": "Carnivore", "conservation_code": "LC", "continent_code": "EU", "biome": "Ocean", "environment_type": "marine",
     "lifespan": "~5 years", "average_weight": "150-275 kg",
     "description": "One of the largest invertebrates ever recorded, reaching up to 13 m in length. First filmed alive in its deep-sea habitat in 2004.",
     "habitat_summary": "Mesopelagic to bathypelagic zones, 300-1000 m depth, in all oceans.",
     "wiki_title": "Giant squid",
     "countries": ["JP", "NZ", "ES"], "occurrences": [(35.0, 139.0), (-41.0, 175.0)]},

    {"common_name": "Goblin Shark", "scientific_name": "Mitsukurina owstoni",
     "class_name": "Chondrichthyes", "order_name": "Lamniformes", "family_name": "Mitsukurinidae", "genus": "Mitsukurina",
     "diet": "Carnivore", "conservation_code": "LC", "continent_code": "AS", "biome": "Ocean", "environment_type": "marine",
     "lifespan": "~36 years", "average_weight": "~210 kg",
     "description": "A living fossil with a lineage extending back 125 million years. Its distinctive snout and protruding, nail-like teeth make it one of the most bizarre deep-sea predators.",
     "habitat_summary": "Continental slopes at 200-1300 m depth, primarily around Japan and the Gulf of Mexico.",
     "wiki_title": "Goblin shark",
     "countries": ["JP", "AU", "US"], "occurrences": [(35.0, 140.0), (-33.0, 152.0)]},

    {"common_name": "Dumbo Octopus", "scientific_name": "Grimpoteuthis spp.",
     "class_name": "Cephalopoda", "order_name": "Octopoda", "family_name": "Opisthoteuthidae", "genus": "Grimpoteuthis",
     "diet": "Carnivore", "conservation_code": "LC", "continent_code": "NA", "biome": "Ocean", "environment_type": "marine",
     "lifespan": "3-5 years", "average_weight": "~6 kg",
     "description": "Named for their ear-like fins resembling Disney's Dumbo, these are the deepest-living octopuses, found at depths up to 7,000 metres.",
     "habitat_summary": "Abyssal and hadal ocean zones, 3000-7000 m depth.",
     "wiki_title": "Grimpoteuthis",
     "countries": ["US", "NZ", "AU"], "occurrences": [(28.0, -88.0), (-45.0, 170.0)]},

    {"common_name": "Colossal Squid", "scientific_name": "Mesonychoteuthis hamiltoni",
     "class_name": "Cephalopoda", "order_name": "Oegopsida", "family_name": "Cranchiidae", "genus": "Mesonychoteuthis",
     "diet": "Carnivore", "conservation_code": "LC", "continent_code": "AN", "biome": "Ocean", "environment_type": "marine",
     "lifespan": "~2 years", "average_weight": "~500 kg",
     "description": "The heaviest known invertebrate, with rotating hooks on its tentacles and the largest eyes in the animal kingdom at up to 27 cm diameter.",
     "habitat_summary": "Deep Southern Ocean waters around Antarctica, 1000-2000 m depth.",
     "wiki_title": "Colossal squid",
     "countries": ["NZ"], "occurrences": [(-60.0, 170.0)]},

    {"common_name": "Vampire Squid", "scientific_name": "Vampyroteuthis infernalis",
     "class_name": "Cephalopoda", "order_name": "Vampyromorphida", "family_name": "Vampyroteuthidae", "genus": "Vampyroteuthis",
     "diet": "Omnivore", "conservation_code": "LC", "continent_code": "NA", "biome": "Ocean", "environment_type": "marine",
     "lifespan": "~8 years", "average_weight": "~1 kg",
     "description": "Despite its terrifying name, the vampire squid is a gentle detritivore living in the oxygen minimum zone. It can turn itself 'inside out' to evade predators.",
     "habitat_summary": "Mesopelagic to bathypelagic zones, 600-1200 m depth, in tropical and temperate oceans.",
     "wiki_title": "Vampire squid",
     "countries": ["US", "MX"], "occurrences": [(25.0, -90.0)]},

    {"common_name": "Frilled Shark", "scientific_name": "Chlamydoselachus anguineus",
     "class_name": "Chondrichthyes", "order_name": "Hexanchiformes", "family_name": "Chlamydoselachidae", "genus": "Chlamydoselachus",
     "diet": "Carnivore", "conservation_code": "LC", "continent_code": "AS", "biome": "Ocean", "environment_type": "marine",
     "lifespan": "~25 years", "average_weight": "~90 kg",
     "description": "A living fossil with 300 trident-shaped teeth in 25 rows. Its eel-like body and snake-like strike make it one of the most primitive sharks alive.",
     "habitat_summary": "Continental shelves and slopes at 50-1500 m depth.",
     "wiki_title": "Frilled shark",
     "countries": ["JP", "PT", "AU"], "occurrences": [(35.0, 139.0), (38.7, -9.1)]},

    {"common_name": "Barreleye Fish", "scientific_name": "Macropinna microstoma",
     "class_name": "Actinopterygii", "order_name": "Argentiniformes", "family_name": "Opisthoproctidae", "genus": "Macropinna",
     "diet": "Carnivore", "conservation_code": "LC", "continent_code": "NA", "biome": "Ocean", "environment_type": "marine",
     "lifespan": "Unknown", "average_weight": "~0.06 kg",
     "description": "Famous for its transparent, fluid-filled dome head through which its tubular green eyes peer upward to spot prey silhouetted against faint light.",
     "habitat_summary": "Mesopelagic zone, 600-800 m depth, in the North Pacific.",
     "wiki_title": "Barreleye",
     "countries": ["US", "JP"], "occurrences": [(36.0, -122.0)]},

    {"common_name": "Giant Isopod", "scientific_name": "Bathynomus giganteus",
     "class_name": "Malacostraca", "order_name": "Isopoda", "family_name": "Cirolanidae", "genus": "Bathynomus",
     "diet": "Omnivore", "conservation_code": "LC", "continent_code": "NA", "biome": "Ocean", "environment_type": "marine",
     "lifespan": "~5 years", "average_weight": "~1.7 kg",
     "description": "A deep-sea crustacean related to woodlice but growing up to 50 cm long. An example of deep-sea gigantism, it can survive years without eating.",
     "habitat_summary": "Benthic zone on the deep ocean floor, 170-2500 m depth.",
     "wiki_title": "Giant isopod",
     "countries": ["US", "MX", "BR"], "occurrences": [(25.0, -90.0)]},

    {"common_name": "Nautilus", "scientific_name": "Nautilus pompilius",
     "class_name": "Cephalopoda", "order_name": "Nautilida", "family_name": "Nautilidae", "genus": "Nautilus",
     "diet": "Carnivore", "conservation_code": "NT", "continent_code": "OC", "biome": "Coral Reef", "environment_type": "marine",
     "lifespan": "~20 years", "average_weight": "~1 kg",
     "description": "A living fossil virtually unchanged for 500 million years. Its spiral shell contains gas-filled chambers for buoyancy control.",
     "habitat_summary": "Coral reef slopes in the Indo-Pacific, 100-700 m depth.",
     "wiki_title": "Nautilus",
     "countries": ["PH", "PG", "AU", "FJ"], "occurrences": [(10.0, 124.0), (-5.0, 152.0)]},

    {"common_name": "Coelacanth", "scientific_name": "Latimeria chalumnae",
     "class_name": "Actinistia", "order_name": "Coelacanthiformes", "family_name": "Latimeriidae", "genus": "Latimeria",
     "diet": "Carnivore", "conservation_code": "CR", "continent_code": "AF", "biome": "Ocean", "environment_type": "marine",
     "lifespan": "~60 years", "average_weight": "80 kg",
     "description": "Thought to have been extinct for 66 million years until a living specimen was caught in 1938. Often called a 'living fossil'.",
     "habitat_summary": "Deep volcanic rock caves at 150-700 m depth off the east coast of Africa.",
     "wiki_title": "Coelacanth",
     "countries": ["ZA", "MZ"], "occurrences": [(-32.0, 29.0), (-12.2, 44.3)]},

    {"common_name": "Oarfish", "scientific_name": "Regalecus glesne",
     "class_name": "Actinopterygii", "order_name": "Lampriformes", "family_name": "Regalecidae", "genus": "Regalecus",
     "diet": "Carnivore", "conservation_code": "LC", "continent_code": "NA", "biome": "Ocean", "environment_type": "marine",
     "lifespan": "Unknown", "average_weight": "~270 kg",
     "description": "The longest bony fish in the world, reaching up to 11 metres. Its serpentine shape likely inspired legends of sea serpents throughout history.",
     "habitat_summary": "Mesopelagic zone, 200-1000 m depth, in temperate and tropical oceans worldwide.",
     "wiki_title": "Oarfish",
     "countries": ["US", "JP", "AU"], "occurrences": [(33.0, -117.0), (35.0, 140.0)]},

    {"common_name": "Sunfish", "scientific_name": "Mola mola",
     "class_name": "Actinopterygii", "order_name": "Tetraodontiformes", "family_name": "Molidae", "genus": "Mola",
     "diet": "Omnivore", "conservation_code": "VU", "continent_code": "EU", "biome": "Ocean", "environment_type": "marine",
     "lifespan": "~10 years", "average_weight": "1000 kg",
     "description": "The heaviest known bony fish, weighing up to 2300 kg. Despite its size, it feeds primarily on jellyfish and can produce 300 million eggs at once.",
     "habitat_summary": "Temperate and tropical open oceans worldwide, surface to 600 m depth.",
     "wiki_title": "Ocean sunfish",
     "countries": ["PT", "ES", "JP", "AU"], "occurrences": [(38.0, -9.0), (35.0, 140.0)]},

    {"common_name": "Leafy Sea Dragon", "scientific_name": "Phycodurus eques",
     "class_name": "Actinopterygii", "order_name": "Syngnathiformes", "family_name": "Syngnathidae", "genus": "Phycodurus",
     "diet": "Carnivore", "conservation_code": "NT", "continent_code": "OC", "biome": "Ocean", "environment_type": "marine",
     "lifespan": "5-10 years", "average_weight": "~0.1 kg",
     "description": "One of the ocean's most ornate creatures, with leaf-shaped appendages providing perfect camouflage among seaweed and kelp.",
     "habitat_summary": "Temperate coastal waters of southern and western Australia, 3-50 m depth.",
     "wiki_title": "Leafy seadragon",
     "countries": ["AU"], "occurrences": [(-35.0, 136.0)]},

    {"common_name": "Blue-ringed Octopus", "scientific_name": "Hapalochlaena lunulata",
     "class_name": "Cephalopoda", "order_name": "Octopoda", "family_name": "Octopodidae", "genus": "Hapalochlaena",
     "diet": "Carnivore", "conservation_code": "LC", "continent_code": "OC", "biome": "Coral Reef", "environment_type": "marine",
     "lifespan": "~2 years", "average_weight": "10-28 g",
     "description": "Despite being only 12-20 cm across, the blue-ringed octopus carries enough venom to kill 26 adults within minutes. There is no known antivenom.",
     "habitat_summary": "Shallow tide pools and coral reefs of the Pacific and Indian Oceans.",
     "wiki_title": "Blue-ringed octopus",
     "countries": ["AU", "JP", "ID", "PH"], "occurrences": [(-33.9, 151.2), (34.0, 132.0)]},

    {"common_name": "Japanese Spider Crab", "scientific_name": "Macrocheira kaempferi",
     "class_name": "Malacostraca", "order_name": "Decapoda", "family_name": "Inachidae", "genus": "Macrocheira",
     "diet": "Omnivore", "conservation_code": "LC", "continent_code": "AS", "biome": "Ocean", "environment_type": "marine",
     "lifespan": "~100 years", "average_weight": "16-20 kg",
     "description": "The largest living arthropod with a leg span of up to 3.7 metres. Despite its enormous size, it is gentle and slow-moving.",
     "habitat_summary": "Deep waters off the Pacific coast of Japan, 50-600 m depth.",
     "wiki_title": "Japanese spider crab",
     "countries": ["JP"], "occurrences": [(35.0, 139.0)]},

    {"common_name": "Mantis Shrimp", "scientific_name": "Odontodactylus scyllarus",
     "class_name": "Malacostraca", "order_name": "Stomatopoda", "family_name": "Odontodactylidae", "genus": "Odontodactylus",
     "diet": "Carnivore", "conservation_code": "LC", "continent_code": "AS", "biome": "Coral Reef", "environment_type": "marine",
     "lifespan": "3-6 years", "average_weight": "~0.2 kg",
     "description": "Possesses the fastest punch in the animal kingdom at 23 m/s, creating cavitation bubbles that reach 4700°C. Has the most complex eyes of any animal with 16 colour receptors.",
     "habitat_summary": "Tropical and subtropical coral reefs of the Indo-Pacific.",
     "wiki_title": "Mantis shrimp",
     "countries": ["ID", "PH", "AU", "TH"], "occurrences": [(-8.0, 115.0), (10.0, 124.0)]},

    {"common_name": "Gulper Eel", "scientific_name": "Eurypharynx pelecanoides",
     "class_name": "Actinopterygii", "order_name": "Saccopharyngiformes", "family_name": "Eurypharyngidae", "genus": "Eurypharynx",
     "diet": "Carnivore", "conservation_code": "LC", "continent_code": "NA", "biome": "Ocean", "environment_type": "marine",
     "lifespan": "Unknown", "average_weight": "Unknown",
     "description": "Also called the pelican eel, it has an enormous hinged mouth much larger than its body, allowing it to swallow prey larger than itself.",
     "habitat_summary": "Bathypelagic to abyssopelagic zones, 500-7625 m depth.",
     "wiki_title": "Pelican eel",
     "countries": ["US"], "occurrences": [(30.0, -80.0)]},

    {"common_name": "Fangtooth Fish", "scientific_name": "Anoplogaster cornuta",
     "class_name": "Actinopterygii", "order_name": "Trachichthyiformes", "family_name": "Anoplogastridae", "genus": "Anoplogaster",
     "diet": "Carnivore", "conservation_code": "LC", "continent_code": "NA", "biome": "Ocean", "environment_type": "marine",
     "lifespan": "Unknown", "average_weight": "~0.12 kg",
     "description": "Despite being only 18 cm long, the fangtooth has the largest teeth relative to body size of any fish. It can survive the crushing pressures at 5000 m depth.",
     "habitat_summary": "Bathypelagic zone, 500-5000 m depth, worldwide.",
     "wiki_title": "Fangtooth",
     "countries": ["US", "AU"], "occurrences": [(28.0, -80.0)]},

    {"common_name": "Blobfish", "scientific_name": "Psychrolutes marcidus",
     "class_name": "Actinopterygii", "order_name": "Scorpaeniformes", "family_name": "Psychrolutidae", "genus": "Psychrolutes",
     "diet": "Carnivore", "conservation_code": "LC", "continent_code": "OC", "biome": "Ocean", "environment_type": "marine",
     "lifespan": "~130 years", "average_weight": "~9 kg",
     "description": "Voted the world's ugliest animal, the blobfish looks perfectly normal at its native depth. Its gelatinous body is slightly less dense than water, allowing it to float above the seafloor.",
     "habitat_summary": "Deep waters off the coasts of Australia and New Zealand, 600-1200 m depth.",
     "wiki_title": "Blobfish",
     "countries": ["AU", "NZ"], "occurrences": [(-38.0, 149.0)]},

    {"common_name": "Mimic Octopus", "scientific_name": "Thaumoctopus mimicus",
     "class_name": "Cephalopoda", "order_name": "Octopoda", "family_name": "Octopodidae", "genus": "Thaumoctopus",
     "diet": "Carnivore", "conservation_code": "LC", "continent_code": "AS", "biome": "Ocean", "environment_type": "marine",
     "lifespan": "~2 years", "average_weight": "~0.5 kg",
     "description": "The only known animal to impersonate multiple species. It can mimic lionfish, flatfish, sea snakes, and at least 12 other animals by changing shape and colour.",
     "habitat_summary": "Sandy bottoms and estuaries of the Indo-Pacific, 1-15 m depth.",
     "wiki_title": "Mimic octopus",
     "countries": ["ID", "MY", "PH"], "occurrences": [(-5.0, 115.0)]},

    {"common_name": "Chambered Nautilus", "scientific_name": "Nautilus pompilius",
     "class_name": "Cephalopoda", "order_name": "Nautilida", "family_name": "Nautilidae", "genus": "Nautilus",
     "diet": "Carnivore", "conservation_code": "NT", "continent_code": "OC", "biome": "Ocean", "environment_type": "marine",
     "lifespan": "~20 years", "average_weight": "~1.2 kg",
     "description": "A 500-million-year-old design that inspired submarines. Uses jet propulsion and adjusts gas in its shell chambers for depth control.",
     "habitat_summary": "Deep tropical Indo-Pacific reef slopes, 150-700 m.",
     "wiki_title": "Chambered nautilus",
     "countries": ["PH", "PG", "FJ"], "occurrences": [(10.0, 124.0)]},

    {"common_name": "Hatchetfish", "scientific_name": "Argyropelecus aculeatus",
     "class_name": "Actinopterygii", "order_name": "Stomiiformes", "family_name": "Sternoptychidae", "genus": "Argyropelecus",
     "diet": "Carnivore", "conservation_code": "LC", "continent_code": "NA", "biome": "Ocean", "environment_type": "marine",
     "lifespan": "~1 year", "average_weight": "~0.01 kg",
     "description": "Uses bioluminescent photophores on its belly to match the faint light from above, making it invisible to predators looking up — a technique called counter-illumination.",
     "habitat_summary": "Mesopelagic zone, 200-1000 m depth, worldwide.",
     "wiki_title": "Hatchetfish",
     "countries": ["US", "BR", "JP"], "occurrences": [(30.0, -75.0)]},

    {"common_name": "Viperfish", "scientific_name": "Chauliodus sloani",
     "class_name": "Actinopterygii", "order_name": "Stomiiformes", "family_name": "Stomiidae", "genus": "Chauliodus",
     "diet": "Carnivore", "conservation_code": "LC", "continent_code": "EU", "biome": "Ocean", "environment_type": "marine",
     "lifespan": "~15 years", "average_weight": "~0.03 kg",
     "description": "Has fang-like teeth so long they curve back past the eyes. Uses a bioluminescent lure on its dorsal spine to attract prey in total darkness.",
     "habitat_summary": "Bathypelagic zone, 250-5000 m depth, in tropical and temperate oceans.",
     "wiki_title": "Viperfish",
     "countries": ["PT", "GB", "US"], "occurrences": [(40.0, -30.0)]},
]
