"""Seed script to populate initial data without external API calls."""
import asyncio
from sqlalchemy.ext.asyncio import create_async_engine, async_sessionmaker, AsyncSession
from app.db.base_all import Base
from app.core.config import get_settings
from app.core.security import hash_password
from app.models.user import User
from app.models.continent import Continent
from app.models.conservation import ConservationStatus
from app.models.behavior import Behavior
from app.models.animal import Animal
from app.models.occurrence import Occurrence
from app.models.country import Country
from app.models.image import Image
from app.models.fact import Fact
from app.utils.slug import slugify

settings = get_settings()

CONTINENTS = [
    ("Africa", "AF", "The world's second-largest continent, home to incredible biodiversity."),
    ("Antarctica", "AN", "The coldest continent, inhabited by penguins, seals, and seabirds."),
    ("Asia", "AS", "The largest continent with diverse ecosystems from tundra to tropics."),
    ("Europe", "EU", "Rich temperate forests and Mediterranean ecosystems."),
    ("North America", "NA", "From arctic tundra to tropical rainforests."),
    ("Oceania", "OC", "Unique island ecosystems with many endemic species."),
    ("South America", "SA", "Home to the Amazon rainforest and extraordinary wildlife."),
]

CONSERVATION_STATUSES = [
    ("LC", "Least Concern", 1),
    ("NT", "Near Threatened", 2),
    ("VU", "Vulnerable", 3),
    ("EN", "Endangered", 4),
    ("CR", "Critically Endangered", 5),
    ("EW", "Extinct in the Wild", 6),
    ("EX", "Extinct", 7),
]

BEHAVIORS = [
    ("social", "Social Behavior"),
    ("hunting", "Hunting / Foraging"),
    ("territoriality", "Territoriality"),
    ("mating", "Mating"),
    ("parenting", "Parenting"),
    ("migration", "Migration"),
    ("defense", "Defense"),
    ("nesting", "Nesting / Denning"),
    ("activity_cycle", "Activity Cycle"),
    ("intelligence", "Intelligence / Tool Use"),
    ("human_interaction", "Human Interaction"),
]

SEED_ANIMALS = [
    {
        "common_name": "African Elephant",
        "scientific_name": "Loxodonta africana",
        "class_name": "Mammalia",
        "order_name": "Proboscidea",
        "family_name": "Elephantidae",
        "genus": "Loxodonta",
        "diet": "Herbivore",
        "lifespan": "60-70 years",
        "average_weight": "6000 kg",
        "average_length": "6-7.5 m",
        "habitat_summary": "Savannas, forests, deserts, and marshes across sub-Saharan Africa",
        "description": "The African elephant is the largest living land animal, known for its intelligence, complex social structures, and iconic tusks.",
        "behavior_summary": "Highly social, living in matriarchal herds. Known for mourning their dead and exceptional memory.",
        "reproduction": "Gestation period of 22 months, the longest of any land animal.",
        "predators": "Lions (calves), humans",
        "prey": "N/A - herbivore",
        "social_structure": "Matriarchal herds of 8-100 individuals",
        "activity_period": "Diurnal",
        "environment_type": "terrestrial",
        "biome": "Savanna",
        "conservation_code": "VU",
        "continent_code": "AF",
        "popularity": 95,
        "fun_facts": "Elephants can recognize themselves in mirrors. They communicate using infrasound over distances up to 10km.",
        "hero_image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/37/African_Bush_Elephant.jpg/1280px-African_Bush_Elephant.jpg",
        "thumbnail_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/37/African_Bush_Elephant.jpg/320px-African_Bush_Elephant.jpg",
        "wiki_summary": "The African bush elephant is the largest living terrestrial animal, with bulls reaching a shoulder height of up to 3.96 m and a body mass of up to 10.4 t.",
        "occurrences": [(-1.29, 36.82), (-2.33, 34.83), (-15.42, 28.28), (-19.84, 23.27), (0.33, 32.58)],
    },
    {
        "common_name": "Bengal Tiger",
        "scientific_name": "Panthera tigris tigris",
        "class_name": "Mammalia",
        "order_name": "Carnivora",
        "family_name": "Felidae",
        "genus": "Panthera",
        "diet": "Carnivore",
        "lifespan": "8-10 years (wild)",
        "average_weight": "220 kg",
        "average_length": "2.7-3.1 m",
        "habitat_summary": "Tropical and subtropical forests, mangroves, and grasslands of the Indian subcontinent",
        "description": "The Bengal tiger is the most numerous tiger subspecies and one of the biggest wild cats alive today.",
        "behavior_summary": "Solitary and territorial. Excellent swimmers and often cool off in streams and lakes.",
        "reproduction": "Gestation period of ~104 days; litters of 2-4 cubs.",
        "predators": "Humans",
        "prey": "Deer, wild boar, buffalo, monkeys",
        "social_structure": "Solitary",
        "activity_period": "Nocturnal",
        "environment_type": "terrestrial",
        "biome": "Tropical Forest",
        "conservation_code": "EN",
        "continent_code": "AS",
        "popularity": 92,
        "fun_facts": "No two tigers have the same stripe pattern. Tigers can leap forward up to 10 meters.",
        "hero_image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/17/Tiger_in_Ranthambhore.jpg/1280px-Tiger_in_Ranthambhore.jpg",
        "thumbnail_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/17/Tiger_in_Ranthambhore.jpg/320px-Tiger_in_Ranthambhore.jpg",
        "wiki_summary": "The Bengal tiger is a population of the Panthera tigris tigris subspecies and the nominate tiger subspecies.",
        "occurrences": [(26.85, 80.91), (23.47, 87.02), (27.49, 89.64), (21.15, 79.08), (28.60, 83.59)],
    },
    {
        "common_name": "Blue Whale",
        "scientific_name": "Balaenoptera musculus",
        "class_name": "Mammalia",
        "order_name": "Artiodactyla",
        "family_name": "Balaenopteridae",
        "genus": "Balaenoptera",
        "diet": "Carnivore",
        "lifespan": "80-90 years",
        "average_weight": "140000 kg",
        "average_length": "25-30 m",
        "habitat_summary": "All major oceans worldwide",
        "description": "The blue whale is the largest animal known to have ever existed, reaching lengths of up to 30 metres.",
        "behavior_summary": "Generally solitary or in pairs. Known for their incredible long-distance vocalizations.",
        "reproduction": "Gestation ~11 months; single calf born every 2-3 years.",
        "predators": "Orcas (rarely)",
        "prey": "Krill",
        "social_structure": "Solitary or pairs",
        "activity_period": "Diurnal",
        "environment_type": "marine",
        "biome": "Ocean",
        "conservation_code": "EN",
        "continent_code": "AN",
        "popularity": 88,
        "fun_facts": "A blue whale's heart is the size of a small car. Their calls can be heard over 1,600 km away.",
        "hero_image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1c/Anim1754_-_Flickr_-_NOAA_Photo_Library.jpg/1280px-Anim1754_-_Flickr_-_NOAA_Photo_Library.jpg",
        "thumbnail_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1c/Anim1754_-_Flickr_-_NOAA_Photo_Library.jpg/320px-Anim1754_-_Flickr_-_NOAA_Photo_Library.jpg",
        "wiki_summary": "The blue whale is a marine mammal and a baleen whale. Reaching a maximum confirmed length of 29.9 metres and weighing up to 199 tonnes, it is the largest animal known ever to have existed.",
        "occurrences": [(-33.86, 18.42), (34.05, -118.24), (64.13, -21.90), (-34.60, -58.38), (35.68, 139.69)],
    },
    {
        "common_name": "Red Fox",
        "scientific_name": "Vulpes vulpes",
        "class_name": "Mammalia",
        "order_name": "Carnivora",
        "family_name": "Canidae",
        "genus": "Vulpes",
        "diet": "Omnivore",
        "lifespan": "2-5 years (wild)",
        "average_weight": "5-7 kg",
        "average_length": "45-90 cm",
        "habitat_summary": "Forests, grasslands, mountains, deserts, and urban areas across the Northern Hemisphere",
        "description": "The red fox is the largest of the true foxes and one of the most widely distributed carnivores in the world.",
        "behavior_summary": "Primarily solitary. Highly adaptable and intelligent, thriving in urban environments.",
        "reproduction": "Gestation ~52 days; litters of 4-6 kits.",
        "predators": "Eagles, wolves, coyotes",
        "prey": "Rabbits, rodents, birds, insects, fruit",
        "social_structure": "Solitary or mated pairs",
        "activity_period": "Crepuscular",
        "environment_type": "terrestrial",
        "biome": "Temperate Forest",
        "conservation_code": "LC",
        "continent_code": "EU",
        "popularity": 78,
        "fun_facts": "Red foxes can hear a watch ticking 40 yards away. They use Earth's magnetic field to hunt.",
        "hero_image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/Vulpes_vulpes_schrencki_7425.jpg/1280px-Vulpes_vulpes_schrencki_7425.jpg",
        "thumbnail_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/Vulpes_vulpes_schrencki_7425.jpg/320px-Vulpes_vulpes_schrencki_7425.jpg",
        "wiki_summary": "The red fox is the largest of the true foxes and one of the most widely distributed members of the order Carnivora.",
        "occurrences": [(51.50, -0.12), (48.85, 2.35), (55.75, 37.61), (40.71, -74.00), (35.68, 139.69)],
    },
    {
        "common_name": "Gray Wolf",
        "scientific_name": "Canis lupus",
        "class_name": "Mammalia",
        "order_name": "Carnivora",
        "family_name": "Canidae",
        "genus": "Canis",
        "diet": "Carnivore",
        "lifespan": "6-8 years (wild)",
        "average_weight": "30-80 kg",
        "average_length": "1.0-1.6 m",
        "habitat_summary": "Forests, tundra, grasslands, and mountains of the Northern Hemisphere",
        "description": "The gray wolf is the largest wild member of the Canidae family, known for its complex pack social structure.",
        "behavior_summary": "Pack animal with complex hierarchies. Cooperative hunters capable of taking down large prey.",
        "reproduction": "Gestation ~63 days; litters of 4-6 pups. Only the alpha pair typically breeds.",
        "predators": "Humans, bears (occasionally)",
        "prey": "Elk, deer, moose, bison",
        "social_structure": "Pack of 5-10 individuals",
        "activity_period": "Crepuscular",
        "environment_type": "terrestrial",
        "biome": "Boreal Forest",
        "conservation_code": "LC",
        "continent_code": "NA",
        "popularity": 85,
        "fun_facts": "Wolves can run at speeds up to 65 km/h. A wolf's howl can be heard up to 16 km away.",
        "hero_image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5f/Kolm%C3%A5rden_Wolf.jpg/1280px-Kolm%C3%A5rden_Wolf.jpg",
        "thumbnail_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5f/Kolm%C3%A5rden_Wolf.jpg/320px-Kolm%C3%A5rden_Wolf.jpg",
        "wiki_summary": "The wolf, also known as the gray wolf or grey wolf, is a large canine native to Eurasia and North America.",
        "occurrences": [(44.42, -110.58), (61.21, -149.90), (64.84, 27.98), (46.87, 8.10), (56.83, 60.60)],
    },
    {
        "common_name": "Bald Eagle",
        "scientific_name": "Haliaeetus leucocephalus",
        "class_name": "Aves",
        "order_name": "Accipitriformes",
        "family_name": "Accipitridae",
        "genus": "Haliaeetus",
        "diet": "Carnivore",
        "lifespan": "20-30 years",
        "average_weight": "3-6.3 kg",
        "average_length": "70-102 cm",
        "habitat_summary": "Near large bodies of open water across North America",
        "description": "The bald eagle is a bird of prey found in North America and the national bird of the United States.",
        "behavior_summary": "Opportunistic feeder, primarily fish. Builds massive nests reused for years.",
        "reproduction": "Lays 1-3 eggs; incubation ~35 days.",
        "predators": "Great horned owls (juveniles), raccoons (eggs)",
        "prey": "Fish, waterfowl, small mammals",
        "social_structure": "Monogamous pairs",
        "activity_period": "Diurnal",
        "environment_type": "aerial",
        "biome": "Temperate Forest",
        "conservation_code": "LC",
        "continent_code": "NA",
        "popularity": 80,
        "fun_facts": "Bald eagles can see fish from over a mile away. Their nests can weigh up to 2 tons.",
        "hero_image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/About_to_Launch_%2826075320352%29.jpg/1280px-About_to_Launch_%2826075320352%29.jpg",
        "thumbnail_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/About_to_Launch_%2826075320352%29.jpg/320px-About_to_Launch_%2826075320352%29.jpg",
        "wiki_summary": "The bald eagle is a bird of prey found in North America. A sea eagle, it has two known subspecies.",
        "occurrences": [(47.60, -122.33), (27.95, -82.46), (58.30, -134.42), (44.97, -93.27), (38.90, -77.04)],
    },
    {
        "common_name": "Giant Panda",
        "scientific_name": "Ailuropoda melanoleuca",
        "class_name": "Mammalia",
        "order_name": "Carnivora",
        "family_name": "Ursidae",
        "genus": "Ailuropoda",
        "diet": "Herbivore",
        "lifespan": "20 years (wild)",
        "average_weight": "70-120 kg",
        "average_length": "1.2-1.9 m",
        "habitat_summary": "Temperate broadleaf and mixed forests of central China",
        "description": "The giant panda is a bear species endemic to China, recognized by its bold black-and-white coat.",
        "behavior_summary": "Solitary, spending most time eating bamboo. Excellent tree climbers despite their size.",
        "reproduction": "Gestation 95-160 days; usually one cub (twins possible but only one typically survives).",
        "predators": "Jackals, snow leopards (cubs)",
        "prey": "N/A - primarily bamboo",
        "social_structure": "Solitary",
        "activity_period": "Crepuscular",
        "environment_type": "terrestrial",
        "biome": "Temperate Forest",
        "conservation_code": "VU",
        "continent_code": "AS",
        "popularity": 93,
        "fun_facts": "Pandas spend 10-16 hours a day eating. A panda's diet is 99% bamboo.",
        "hero_image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/Grosser_Panda.JPG/1280px-Grosser_Panda.JPG",
        "thumbnail_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/Grosser_Panda.JPG/320px-Grosser_Panda.JPG",
        "wiki_summary": "The giant panda, also known as the panda bear, is a bear species endemic to China.",
        "occurrences": [(30.57, 104.07), (33.43, 108.37), (31.07, 103.63), (29.56, 106.55), (30.67, 104.06)],
    },
    {
        "common_name": "Polar Bear",
        "scientific_name": "Ursus maritimus",
        "class_name": "Mammalia",
        "order_name": "Carnivora",
        "family_name": "Ursidae",
        "genus": "Ursus",
        "diet": "Carnivore",
        "lifespan": "25-30 years",
        "average_weight": "350-700 kg",
        "average_length": "2.4-3 m",
        "habitat_summary": "Arctic sea ice, coastlines, and islands throughout the Arctic Circle",
        "description": "The polar bear is a hypercarnivorous bear whose native range lies largely within the Arctic Circle.",
        "behavior_summary": "Excellent swimmers, spending much time hunting seals on sea ice. Generally solitary outside mating season.",
        "reproduction": "Gestation ~8 months including delayed implantation; 1-3 cubs born in snow dens.",
        "predators": "Humans, orcas (rarely)",
        "prey": "Ringed seals, bearded seals, walruses",
        "social_structure": "Solitary",
        "activity_period": "Diurnal",
        "environment_type": "terrestrial",
        "biome": "Arctic Tundra",
        "conservation_code": "VU",
        "continent_code": "NA",
        "popularity": 90,
        "fun_facts": "Polar bear fur is actually transparent, not white. Their skin is black to absorb heat.",
        "hero_image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/66/Polar_Bear_-_Alaska_%28cropped%29.jpg/1280px-Polar_Bear_-_Alaska_%28cropped%29.jpg",
        "thumbnail_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/66/Polar_Bear_-_Alaska_%28cropped%29.jpg/320px-Polar_Bear_-_Alaska_%28cropped%29.jpg",
        "wiki_summary": "The polar bear is a hypercarnivorous bear whose native range lies largely within the Arctic Circle.",
        "occurrences": [(78.22, 15.63), (58.77, -94.17), (71.29, -156.78), (69.65, 18.95), (74.00, 40.00)],
    },
    {
        "common_name": "Cheetah",
        "scientific_name": "Acinonyx jubatus",
        "class_name": "Mammalia",
        "order_name": "Carnivora",
        "family_name": "Felidae",
        "genus": "Acinonyx",
        "diet": "Carnivore",
        "lifespan": "10-12 years (wild)",
        "average_weight": "21-72 kg",
        "average_length": "1.1-1.5 m",
        "habitat_summary": "Open grasslands and savannas of Africa and parts of Iran",
        "description": "The cheetah is the fastest land animal, capable of reaching speeds up to 112 km/h in short bursts.",
        "behavior_summary": "Diurnal hunter using speed rather than ambush. Males form small coalitions; females are solitary.",
        "reproduction": "Gestation ~93 days; litters of 3-5 cubs.",
        "predators": "Lions, hyenas, leopards",
        "prey": "Gazelles, impalas, hares",
        "social_structure": "Males in coalitions; females solitary",
        "activity_period": "Diurnal",
        "environment_type": "terrestrial",
        "biome": "Savanna",
        "conservation_code": "VU",
        "continent_code": "AF",
        "popularity": 87,
        "fun_facts": "Cheetahs can accelerate from 0 to 100 km/h in just 3 seconds. They cannot roar but can purr.",
        "hero_image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/11/Cheetah_Kruger.jpg/1280px-Cheetah_Kruger.jpg",
        "thumbnail_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/11/Cheetah_Kruger.jpg/320px-Cheetah_Kruger.jpg",
        "wiki_summary": "The cheetah is a large cat native to Africa and central Iran. It is the fastest land animal.",
        "occurrences": [(-1.95, 30.06), (-24.66, 25.91), (-2.50, 34.75), (9.02, 38.75), (-15.39, 28.32)],
    },
    {
        "common_name": "Emperor Penguin",
        "scientific_name": "Aptenodytes forsteri",
        "class_name": "Aves",
        "order_name": "Sphenisciformes",
        "family_name": "Spheniscidae",
        "genus": "Aptenodytes",
        "diet": "Carnivore",
        "lifespan": "15-20 years",
        "average_weight": "22-45 kg",
        "average_length": "1.1-1.3 m",
        "habitat_summary": "Antarctic ice and surrounding Southern Ocean waters",
        "description": "The emperor penguin is the tallest and heaviest of all living penguin species, endemic to Antarctica.",
        "behavior_summary": "Highly social, breeding in large colonies. Males incubate eggs through Antarctic winter.",
        "reproduction": "Single egg; incubated by male for ~65 days in extreme cold.",
        "predators": "Leopard seals, giant petrels, orcas",
        "prey": "Fish, squid, krill",
        "social_structure": "Large breeding colonies",
        "activity_period": "Diurnal",
        "environment_type": "marine",
        "biome": "Antarctic",
        "conservation_code": "NT",
        "continent_code": "AN",
        "popularity": 82,
        "fun_facts": "Emperor penguins can dive to depths of 500 meters and hold their breath for over 20 minutes.",
        "hero_image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/07/Emperor_Penguin_Manchot_empereur.jpg/800px-Emperor_Penguin_Manchot_empereur.jpg",
        "thumbnail_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/07/Emperor_Penguin_Manchot_empereur.jpg/320px-Emperor_Penguin_Manchot_empereur.jpg",
        "wiki_summary": "The emperor penguin is the tallest and heaviest of all living penguin species and is endemic to Antarctica.",
        "occurrences": [(-77.85, 166.67), (-67.60, 62.87), (-72.00, 2.53), (-66.28, 110.52), (-70.67, -8.25)],
    },
    {
        "common_name": "Komodo Dragon",
        "scientific_name": "Varanus komodoensis",
        "class_name": "Reptilia",
        "order_name": "Squamata",
        "family_name": "Varanidae",
        "genus": "Varanus",
        "diet": "Carnivore",
        "lifespan": "30 years",
        "average_weight": "70 kg",
        "average_length": "2.6 m",
        "habitat_summary": "Indonesian islands of Komodo, Rinca, Flores, and Gili Motang",
        "description": "The Komodo dragon is the largest living species of lizard, found on several Indonesian islands.",
        "behavior_summary": "Ambush predator with venomous bite. Solitary and highly territorial.",
        "reproduction": "Lays ~20 eggs; incubation ~8 months. Capable of parthenogenesis.",
        "predators": "None (apex predator); juveniles preyed on by adults",
        "prey": "Deer, pigs, water buffalo, smaller dragons",
        "social_structure": "Solitary",
        "activity_period": "Diurnal",
        "environment_type": "terrestrial",
        "biome": "Tropical Savanna",
        "conservation_code": "EN",
        "continent_code": "AS",
        "popularity": 76,
        "fun_facts": "Komodo dragons can eat up to 80% of their body weight in a single meal.",
        "hero_image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Komodo_dragon_%28Varanus_komodoensis%29.jpg/1280px-Komodo_dragon_%28Varanus_komodoensis%29.jpg",
        "thumbnail_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Komodo_dragon_%28Varanus_komodoensis%29.jpg/320px-Komodo_dragon_%28Varanus_komodoensis%29.jpg",
        "wiki_summary": "The Komodo dragon is the largest extant species of lizard, growing to a maximum length of 3 metres.",
        "occurrences": [(-8.55, 119.44), (-8.65, 119.50), (-8.47, 119.88), (-8.58, 119.49), (-8.52, 119.46)],
    },
    {
        "common_name": "Snow Leopard",
        "scientific_name": "Panthera uncia",
        "class_name": "Mammalia",
        "order_name": "Carnivora",
        "family_name": "Felidae",
        "genus": "Panthera",
        "diet": "Carnivore",
        "lifespan": "10-12 years (wild)",
        "average_weight": "22-55 kg",
        "average_length": "0.86-1.25 m",
        "habitat_summary": "Alpine and subalpine zones of Central and South Asia at elevations of 3,000-4,500m",
        "description": "The snow leopard is a large cat native to the mountain ranges of Central and South Asia.",
        "behavior_summary": "Solitary and elusive. Crepuscular hunter adapted to steep, rugged terrain.",
        "reproduction": "Gestation ~93-110 days; litters of 2-3 cubs.",
        "predators": "Humans, wolves (rarely)",
        "prey": "Blue sheep, ibex, marmots, pikas",
        "social_structure": "Solitary",
        "activity_period": "Crepuscular",
        "environment_type": "terrestrial",
        "biome": "Alpine",
        "conservation_code": "VU",
        "continent_code": "AS",
        "popularity": 84,
        "fun_facts": "Snow leopards cannot roar. They can leap up to 15 meters in a single bound.",
        "hero_image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/Irbis4.jpg/1280px-Irbis4.jpg",
        "thumbnail_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/Irbis4.jpg/320px-Irbis4.jpg",
        "wiki_summary": "The snow leopard, also known as the ounce, is a large cat native to the mountain ranges of Central and South Asia.",
        "occurrences": [(35.86, 74.89), (42.87, 74.59), (27.99, 86.93), (39.65, 66.96), (47.92, 106.91)],
    },
    {
        "common_name": "Great White Shark",
        "scientific_name": "Carcharodon carcharias",
        "class_name": "Chondrichthyes",
        "order_name": "Lamniformes",
        "family_name": "Lamnidae",
        "genus": "Carcharodon",
        "diet": "Carnivore",
        "lifespan": "70+ years",
        "average_weight": "680-1100 kg",
        "average_length": "4.0-6.1 m",
        "habitat_summary": "Coastal and offshore waters of all major oceans, preferring temperate seas",
        "description": "The great white shark is the world's largest known predatory fish.",
        "behavior_summary": "Apex predator using ambush attacks from below. Migratory, traveling vast ocean distances.",
        "reproduction": "Ovoviviparous; gestation ~11 months; 2-10 pups.",
        "predators": "Orcas",
        "prey": "Seals, sea lions, fish, other sharks",
        "social_structure": "Solitary or loose aggregations",
        "activity_period": "Diurnal",
        "environment_type": "marine",
        "biome": "Ocean",
        "conservation_code": "VU",
        "continent_code": "AF",
        "popularity": 86,
        "fun_facts": "Great whites can detect a single drop of blood in 25 gallons of water from 3 miles away.",
        "hero_image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/56/White_shark.jpg/1280px-White_shark.jpg",
        "thumbnail_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/56/White_shark.jpg/320px-White_shark.jpg",
        "wiki_summary": "The great white shark is a species of large mackerel shark notable for its size, with the largest preserved female specimen measuring 5.83 m in length.",
        "occurrences": [(-34.36, 18.47), (37.77, -122.42), (-33.87, 151.21), (21.31, -157.86), (36.72, -4.42)],
    },
    {
        "common_name": "Red Kangaroo",
        "scientific_name": "Osphranter rufus",
        "class_name": "Mammalia",
        "order_name": "Diprotodontia",
        "family_name": "Macropodidae",
        "genus": "Osphranter",
        "diet": "Herbivore",
        "lifespan": "12-18 years",
        "average_weight": "18-90 kg",
        "average_length": "1.3-1.6 m",
        "habitat_summary": "Arid and semi-arid inland regions of Australia",
        "description": "The red kangaroo is the largest living marsupial and the largest land mammal native to Australia.",
        "behavior_summary": "Social, living in mobs. Males box each other for dominance. Capable of hopping at 56 km/h.",
        "reproduction": "Gestation ~33 days; joey stays in pouch for ~235 days.",
        "predators": "Dingoes, wedge-tailed eagles (joeys)",
        "prey": "N/A - herbivore",
        "social_structure": "Mobs of 2-10",
        "activity_period": "Crepuscular",
        "environment_type": "terrestrial",
        "biome": "Arid Shrubland",
        "conservation_code": "LC",
        "continent_code": "OC",
        "popularity": 74,
        "fun_facts": "Kangaroos can't walk backwards. A group of kangaroos is called a mob.",
        "hero_image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0c/Red_kangaroo_-_melbourne_zoo.jpg/1280px-Red_kangaroo_-_melbourne_zoo.jpg",
        "thumbnail_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0c/Red_kangaroo_-_melbourne_zoo.jpg/320px-Red_kangaroo_-_melbourne_zoo.jpg",
        "wiki_summary": "The red kangaroo is the largest of all kangaroos, the largest terrestrial mammal native to Australia.",
        "occurrences": [(-23.70, 133.87), (-31.95, 141.47), (-26.65, 148.78), (-29.01, 134.75), (-25.27, 130.99)],
    },
    {
        "common_name": "African Lion",
        "scientific_name": "Panthera leo",
        "class_name": "Mammalia",
        "order_name": "Carnivora",
        "family_name": "Felidae",
        "genus": "Panthera",
        "diet": "Carnivore",
        "lifespan": "10-14 years (wild)",
        "average_weight": "150-250 kg",
        "average_length": "1.7-2.5 m",
        "habitat_summary": "Sub-Saharan African savannas, grasslands, and open woodlands",
        "description": "The lion is a large cat of the genus Panthera, native to Africa and India. The African lion is the most social of all wild cat species.",
        "behavior_summary": "Only truly social cat. Lives in prides with cooperative hunting and communal cub-rearing.",
        "reproduction": "Gestation ~110 days; litters of 1-4 cubs.",
        "predators": "Humans, hyenas (cubs)",
        "prey": "Zebras, wildebeest, buffalo, antelope",
        "social_structure": "Prides of 5-30 individuals",
        "activity_period": "Nocturnal",
        "environment_type": "terrestrial",
        "biome": "Savanna",
        "conservation_code": "VU",
        "continent_code": "AF",
        "popularity": 94,
        "fun_facts": "A lion's roar can be heard from 8 km away. Lions sleep up to 20 hours a day.",
        "hero_image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/73/Lion_waiting_in_Namibia.jpg/1280px-Lion_waiting_in_Namibia.jpg",
        "thumbnail_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/73/Lion_waiting_in_Namibia.jpg/320px-Lion_waiting_in_Namibia.jpg",
        "wiki_summary": "The lion is a large cat of the genus Panthera native to Africa and India.",
        "occurrences": [(-2.33, 34.83), (-1.29, 36.82), (-19.17, 15.93), (-15.39, 28.32), (9.08, 7.49)],
    },
    {
        "common_name": "Bottlenose Dolphin",
        "scientific_name": "Tursiops truncatus",
        "class_name": "Mammalia",
        "order_name": "Artiodactyla",
        "family_name": "Delphinidae",
        "genus": "Tursiops",
        "diet": "Carnivore",
        "lifespan": "40-50 years",
        "average_weight": "150-650 kg",
        "average_length": "2.0-4.0 m",
        "habitat_summary": "Temperate and tropical oceans worldwide, coastal and offshore",
        "description": "The common bottlenose dolphin is the most well-known species of the family Delphinidae.",
        "behavior_summary": "Highly social and intelligent. Uses echolocation and cooperative hunting strategies.",
        "reproduction": "Gestation ~12 months; single calf.",
        "predators": "Sharks, orcas",
        "prey": "Fish, squid, shrimp",
        "social_structure": "Pods of 10-30",
        "activity_period": "Diurnal",
        "environment_type": "marine",
        "biome": "Ocean",
        "conservation_code": "LC",
        "continent_code": "NA",
        "popularity": 83,
        "fun_facts": "Dolphins sleep with one eye open. They can recognize themselves in mirrors.",
        "hero_image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Tursiops_truncatus_01.jpg/1280px-Tursiops_truncatus_01.jpg",
        "thumbnail_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Tursiops_truncatus_01.jpg/320px-Tursiops_truncatus_01.jpg",
        "wiki_summary": "The common bottlenose dolphin is the most well-known species of the family Delphinidae.",
        "occurrences": [(25.76, -80.19), (36.85, -75.98), (28.55, -16.25), (-27.47, 153.03), (43.46, 3.79)],
    },
    {
        "common_name": "Humpback Whale",
        "scientific_name": "Megaptera novaeangliae",
        "class_name": "Mammalia",
        "order_name": "Artiodactyla",
        "family_name": "Balaenopteridae",
        "genus": "Megaptera",
        "diet": "Carnivore",
        "lifespan": "45-50 years",
        "average_weight": "25000-30000 kg",
        "average_length": "12-16 m",
        "habitat_summary": "All major oceans; migrates from polar feeding grounds to tropical breeding grounds",
        "description": "The humpback whale is a species of baleen whale known for its spectacular breaching and complex songs.",
        "behavior_summary": "Known for elaborate songs lasting hours. Cooperative bubble-net feeding. Long-distance migrators.",
        "reproduction": "Gestation ~11 months; single calf born in warm waters.",
        "predators": "Orcas",
        "prey": "Krill, small fish",
        "social_structure": "Generally solitary; temporary groups during feeding/migration",
        "activity_period": "Diurnal",
        "environment_type": "marine",
        "biome": "Ocean",
        "conservation_code": "LC",
        "continent_code": "AN",
        "popularity": 79,
        "fun_facts": "Humpback whale songs can travel over 20,000 km through the ocean. Each population has its own unique song.",
        "hero_image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Humpback_stellwagen_edit.jpg/1280px-Humpback_stellwagen_edit.jpg",
        "thumbnail_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Humpback_stellwagen_edit.jpg/320px-Humpback_stellwagen_edit.jpg",
        "wiki_summary": "The humpback whale is a species of baleen whale. It is a member of the family Balaenopteridae.",
        "occurrences": [(21.31, -157.86), (-20.16, 57.50), (-33.86, 18.42), (64.15, -21.95), (42.36, -70.92)],
    },
    {
        "common_name": "Orangutan",
        "scientific_name": "Pongo pygmaeus",
        "class_name": "Mammalia",
        "order_name": "Primates",
        "family_name": "Hominidae",
        "genus": "Pongo",
        "diet": "Omnivore",
        "lifespan": "35-45 years",
        "average_weight": "30-82 kg",
        "average_length": "1.25-1.5 m",
        "habitat_summary": "Tropical rainforests of Borneo and Sumatra",
        "description": "Orangutans are great apes native to the rainforests of Indonesia and Malaysia, known for their intelligence and arboreal lifestyle.",
        "behavior_summary": "Highly intelligent; known tool users. Mostly solitary. Build elaborate sleeping nests each night.",
        "reproduction": "Gestation ~8.5 months; single infant. Longest interbirth interval of any land mammal (~8 years).",
        "predators": "Tigers, clouded leopards",
        "prey": "Fruit, insects, bark, leaves",
        "social_structure": "Solitary (females with offspring)",
        "activity_period": "Diurnal",
        "environment_type": "terrestrial",
        "biome": "Tropical Rainforest",
        "conservation_code": "CR",
        "continent_code": "AS",
        "popularity": 81,
        "fun_facts": "Orangutans share 97% of their DNA with humans. They are the largest arboreal mammals.",
        "hero_image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/be/Orang_Utan%2C_Pair_in_nest.jpg/1280px-Orang_Utan%2C_Pair_in_nest.jpg",
        "thumbnail_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/be/Orang_Utan%2C_Pair_in_nest.jpg/320px-Orang_Utan%2C_Pair_in_nest.jpg",
        "wiki_summary": "Orangutans are great apes native to the rainforests of Indonesia and Malaysia.",
        "occurrences": [(1.49, 110.35), (-0.50, 117.15), (2.95, 99.05), (1.55, 110.34), (0.51, 116.92)],
    },
    {
        "common_name": "Jaguar",
        "scientific_name": "Panthera onca",
        "class_name": "Mammalia",
        "order_name": "Carnivora",
        "family_name": "Felidae",
        "genus": "Panthera",
        "diet": "Carnivore",
        "lifespan": "12-15 years (wild)",
        "average_weight": "56-96 kg",
        "average_length": "1.12-1.85 m",
        "habitat_summary": "Tropical rainforests, swamps, and grasslands from Mexico to Argentina",
        "description": "The jaguar is the largest cat in the Americas and the third-largest in the world.",
        "behavior_summary": "Solitary ambush predator. Strong swimmers; will hunt caimans and anacondas. Has the strongest bite of all big cats.",
        "reproduction": "Gestation ~93-105 days; litters of 1-4 cubs.",
        "predators": "Humans, anacondas (young jaguars)",
        "prey": "Capybaras, deer, caimans, peccaries",
        "social_structure": "Solitary",
        "activity_period": "Crepuscular",
        "environment_type": "terrestrial",
        "biome": "Tropical Rainforest",
        "conservation_code": "NT",
        "continent_code": "SA",
        "popularity": 77,
        "fun_facts": "Jaguars have the strongest bite relative to size of all big cats. The name 'jaguar' comes from 'yaguar' meaning 'he who kills with one leap'.",
        "hero_image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Standing_jaguar.jpg/1280px-Standing_jaguar.jpg",
        "thumbnail_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Standing_jaguar.jpg/320px-Standing_jaguar.jpg",
        "wiki_summary": "The jaguar is a large cat species and the only living member of the genus Panthera native to the Americas.",
        "occurrences": [(-3.47, -62.22), (-16.30, -48.95), (17.99, -88.22), (9.93, -84.08), (-13.16, -72.55)],
    },
    {
        "common_name": "Gorilla",
        "scientific_name": "Gorilla beringei",
        "class_name": "Mammalia",
        "order_name": "Primates",
        "family_name": "Hominidae",
        "genus": "Gorilla",
        "diet": "Herbivore",
        "lifespan": "35-40 years",
        "average_weight": "70-200 kg",
        "average_length": "1.2-1.8 m",
        "habitat_summary": "Tropical and subtropical forests of central Africa",
        "description": "Gorillas are the largest living primates, ground-dwelling and predominantly herbivorous.",
        "behavior_summary": "Social, living in groups led by a dominant silverback male. Gentle despite their size.",
        "reproduction": "Gestation ~8.5 months; single infant. Interbirth interval ~4 years.",
        "predators": "Leopards (rarely), humans",
        "prey": "N/A - herbivore",
        "social_structure": "Groups of 5-30 led by silverback",
        "activity_period": "Diurnal",
        "environment_type": "terrestrial",
        "biome": "Tropical Forest",
        "conservation_code": "CR",
        "continent_code": "AF",
        "popularity": 83,
        "fun_facts": "Gorillas share 98.3% of their DNA with humans. Each gorilla has unique nose prints, like human fingerprints.",
        "hero_image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bb/Gorille_des_montagnes_au_Rwanda.jpg/1280px-Gorille_des_montagnes_au_Rwanda.jpg",
        "thumbnail_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bb/Gorille_des_montagnes_au_Rwanda.jpg/320px-Gorille_des_montagnes_au_Rwanda.jpg",
        "wiki_summary": "Gorillas are herbivorous, predominantly ground-dwelling great apes that inhabit the tropical forests of equatorial Africa.",
        "occurrences": [(-1.94, 29.87), (-2.50, 28.85), (0.33, 32.58), (-4.32, 15.31), (3.85, 11.50)],
    },
]


async def seed_database():
    engine = create_async_engine(settings.DATABASE_URL)
    async with engine.begin() as conn:
        await conn.run_sync(Base.metadata.create_all)

    Session = async_sessionmaker(engine, class_=AsyncSession, expire_on_commit=False)
    async with Session() as db:
        # Admin user
        from sqlalchemy import select
        existing = await db.execute(select(User).where(User.email == settings.ADMIN_EMAIL))
        if not existing.scalar_one_or_none():
            admin = User(
                email=settings.ADMIN_EMAIL,
                username="admin",
                hashed_password=hash_password(settings.ADMIN_PASSWORD),
                is_admin=True,
            )
            db.add(admin)

        # Continents
        continent_map = {}
        for name, code, desc in CONTINENTS:
            existing = await db.execute(select(Continent).where(Continent.code == code))
            c = existing.scalar_one_or_none()
            if not c:
                c = Continent(name=name, code=code, description=desc)
                db.add(c)
                await db.flush()
            continent_map[code] = c

        # Conservation statuses
        cs_map = {}
        for code, name, severity in CONSERVATION_STATUSES:
            existing = await db.execute(select(ConservationStatus).where(ConservationStatus.code == code))
            cs = existing.scalar_one_or_none()
            if not cs:
                cs = ConservationStatus(code=code, name=name, severity=severity)
                db.add(cs)
                await db.flush()
            cs_map[code] = cs

        # Behaviors
        for cat, label in BEHAVIORS:
            existing = await db.execute(select(Behavior).where(Behavior.category == cat))
            if not existing.scalar_one_or_none():
                db.add(Behavior(category=cat, label=label))

        await db.flush()

        # Animals
        for data in SEED_ANIMALS:
            existing = await db.execute(select(Animal).where(Animal.slug == slugify(data["common_name"])))
            if existing.scalar_one_or_none():
                continue

            cs = cs_map.get(data.get("conservation_code"))
            continent = continent_map.get(data.get("continent_code"))

            animal = Animal(
                slug=slugify(data["common_name"]),
                common_name=data["common_name"],
                scientific_name=data.get("scientific_name"),
                class_name=data.get("class_name"),
                order_name=data.get("order_name"),
                family_name=data.get("family_name"),
                genus=data.get("genus"),
                diet=data.get("diet"),
                lifespan=data.get("lifespan"),
                average_weight=data.get("average_weight"),
                average_length=data.get("average_length"),
                habitat_summary=data.get("habitat_summary"),
                description=data.get("description"),
                behavior_summary=data.get("behavior_summary"),
                reproduction=data.get("reproduction"),
                predators=data.get("predators"),
                prey=data.get("prey"),
                social_structure=data.get("social_structure"),
                activity_period=data.get("activity_period"),
                environment_type=data.get("environment_type"),
                biome=data.get("biome"),
                fun_facts=data.get("fun_facts"),
                wiki_summary=data.get("wiki_summary"),
                hero_image_url=data.get("hero_image_url"),
                thumbnail_url=data.get("thumbnail_url"),
                popularity=data.get("popularity", 50),
                conservation_status_id=cs.id if cs else None,
                continent_id=continent.id if continent else None,
                kingdom="Animalia",
            )
            db.add(animal)
            await db.flush()

            # Hero image
            if data.get("hero_image_url"):
                db.add(Image(animal_id=animal.id, url=data["hero_image_url"], is_hero=True, source="wikimedia"))

            # Fun fact
            if data.get("fun_facts"):
                db.add(Fact(animal_id=animal.id, content=data["fun_facts"], source="seed"))

            # Occurrences
            for lat, lon in data.get("occurrences", []):
                db.add(Occurrence(animal_id=animal.id, latitude=lat, longitude=lon, source_name="seed"))

            animal.observation_count = len(data.get("occurrences", []))

        await db.commit()
    await engine.dispose()
    print("Seed complete!")


if __name__ == "__main__":
    asyncio.run(seed_database())
